# List buffs coords
####################################################
STRATEGY_BUFF_CENTER_X = 939
STRATEGY_BUFF_CENTER_Y = 561

SECURITY_BUFF_CENTER_X = 1102
SECURITY_BUFF_CENTER_Y = 561

DEVELOPMENT_BUFF_CENTER_X = 771
DEVELOPMENT_BUFF_CENTER_Y = 790

SCIENCE_BUFF_CENTER_X = 940
SCIENCE_BUFF_CENTER_Y = 790

INTERIOR_BUFF_CENTER_X = 1102
INTERIOR_BUFF_CENTER_Y = 790

#---------------------------------------------------
LIST_BUFF_TOP_LEFT_X = 803 # After profile picture
LIST_BUFF_TOP_LEFT_Y = 226
LIST_BUFF_BOTTOM_RIGHT_X = 1190
LIST_BUFF_BOTTOM_RIGHT_Y = 291

# To get player name text
LIST_BUFF_CENTER_X = 1031
LIST_BUFF_CENTER_Y = 258

#---------------------------------------------------
TIME_IN_THE_BUFF_TOP_LEFT_X = 702
TIME_IN_THE_BUFF_TOP_LEFT_Y = 316

TIME_IN_THE_BUFF_BOTTOM_RIGHT_X = 1171
TIME_IN_THE_BUFF_BOTTOM_RIGHT_Y = 350
####################################################